[[section-system-scope-and-context]]
== System Scope and Context


[role="arc42help"]
****
.Contents
System scope and context - as the name suggests - delimits your system (i.e. your scope) from all its communication partners
(neighboring systems and users, i.e. the context of your system). It thereby specifies the external interfaces.

If necessary, differentiate the business context (domain specific inputs and outputs) from the technical context (channels, protocols, hardware).

.Motivation
The domain interfaces and technical interfaces to communication partners are among your system's most critical aspects. Make sure that you completely understand them.

.Form
Various options:

* Context diagrams
* Lists of communication partners and their interfaces.
****


=== Business Context

[role="arc42help"]
****
.Contents
Specification of *all* communication partners (users, IT-systems, ...) with explanations of domain specific inputs and outputs or interfaces.
Optionally you can add domain specific formats or communication protocols.

.Motivation
All stakeholders should understand which data are exchanged with the environment of the system.

.Form
All kinds of diagrams that show the system as a black box and specify the domain interfaces to communication partners.

Alternatively (or additionally) you can use a table.
The title of the table is the name of your system, the three columns contain the name of the communication partner, the inputs, and the outputs.
****

**<Diagram or Table>**

**<optionally: Explanation of external domain interfaces>**

=== Technical Context

[role="arc42help"]
****
.Contents
Technical interfaces (channels and transmission media) linking your system to its environment. In addition a mapping of domain specific input/output to the channels, i.e. an explanation with I/O uses which channel.

.Motivation
Many stakeholders make architectural decision based on the technical interfaces between the system and its context. Especially infrastructure or hardware designers decide these technical interfaces.

.Form
E.g. UML deployment diagram describing channels to neighboring systems,
together with a mapping table showing the relationships between channels and input/output.

****

**<Diagram or Table>**

**<optionally: Explanation of technical interfaces>**

**<Mapping Input/Output to Channels>**


=== Contexto de negocio

[options="header", cols="1,2,2"]
|===
|Elemento de comunicación|Entrada|Salida
|Usuario|El usuario recibirá una respuesta de la aplicación a través del dispositivo que esté utilizando para acceder a la web|Será el propio usuario el que interactuará con la aplicación
|Solid POD|El Pod será creado por el usuario para poder almacenar la información necesaria|La información solo se mostrará si el usuario es autentificado o se dan permisos para ello
|MongoDB|La base de datos aceptará peticiones de la aplicación|La base de datos responderá a la aplicación con los datos solicitados.
|Google Maps API|La API obtendrá las diferentes ubicaciones del mapa|Nos mostrará información acerca de los lugares (comentarios, fotos, reseñas ...)
|===



=== Contexto Técnico
[%header, cols=2]
|===
|Tecnología utilizada|Descripción
|SOLID|Nos permitirá almacenar de forma segura la información del usuario
|TypeScript|Lenguaje de programación que utlizaremos durante el desarrollo
|React|Biblioteca de JavaScript que se utilizará a la hora de crear las interfaces de nuestra aplicación
|MongoDB|Sistema de base de datos NoSQL, donde almacenaremos los datos de los puntos del mapa
|===