[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== Usuario crea un mapa nuevo
El usuario selecciona la opción de crear un mapa nuevo, es decir, aún no tiene puntos de interés.

[plantuml,"Crear mapa",png]
----
header Runtime View
title Creación de mapas

Actor Usuario
Participant LoMap
Participant Proveedor
Database Pod as "Pod del usuario" #pink

skinparam responseMessageBelowArrow true

...

Usuario -> LoMap: Inicia sesión con su usuario

LoMap -> Proveedor: Solicitar autenticación de la cuenta
LoMap <-- Proveedor: Confirma autenticación de la cuenta

Usuario <-- LoMap: Muestra la página de inicio

Usuario -> LoMap: Selecciona opción de crear mapa

LoMap -> Proveedor: Solicita acceso al pod
Proveedor -> Pod: Envía la información del nuevo mapa
LoMap <-- Proveedor: Confirma la creación del nuevo mapa

Usuario <-- LoMap: Mensaje de confirmación
----

=== Usuario añade un restaurante a su mapa
El usuario añade a uno de sus mapas un restaurante como punto de interés.

[plantuml,"Añadir restaurante",png]
----
header Runtime View
title Añadir puntos de interés

Actor Usuario
Participant LoMap
Participant Proveedor
Database Pod as "Pod del usuario" #pink

skinparam responseMessageBelowArrow true

...

Usuario -> LoMap: Selecciona opción de cargar mapa

LoMap -> Proveedor: Solicita acceso al pod
Proveedor -> Pod: Accede a los datos del mapa
LoMap <-- Proveedor: Devuelve datos del mapa

Usuario <-- LoMap: Muestra estado del mapa seleccionado


Usuario -> LoMap: Selecciona acción de añadir punto de interés
Usuario <-- LoMap: Formulario con los datos del punto de interés

Usuario -> LoMap: Rellena y confirma los datos
LoMap -> Proveedor: Solicita acceso al pod
Proveedor -> Pod: Envía información del nuevo punto de interés

LoMap <-- Proveedor: Confirmación de los datos recibidos
Usuario <-- LoMap: Mensaje de confirmación

----

=== Usuario publica un comentario
El usuario accede a uno de los mapas públicos de uno de sus amigos y deja un comentario en un punto de interés.

[plantuml,"Publicar comentario",png]
----
header Runtime View
title Publicar comentario

Actor Usuario
Participant LoMap
Participant Proveedor
Database Pod as "Pod del usuario" #pink
Database PodAmigo as "Pod del amigo" #lightblue

skinparam responseMessageBelowArrow true

Usuario -> LoMap: Abre lista de amigos

LoMap -> Proveedor: Solicita acceso al pod
Proveedor -> Pod: Accede a la lista de amigos
LoMap <-- Proveedor: Devuelve lista de amigos

Usuario <-- LoMap: Muestra lista de amigos


Usuario -> LoMap: Selecciona mapa de un amigo

LoMap -> Proveedor: Solicita acceso al pod del amigo
Proveedor -> PodAmigo: Accede a los datos del mapa
LoMap <-- Proveedor: Devuelve datos del mapa

Usuario <-- LoMap: Muestra datos del mapa en pantalla

Usuario -> LoMap: Selecciona un punto de interés del mapa

LoMap -> Proveedor: Solicita acceso al pod del amigo
Proveedor -> PodAmigo: Accede a la información del punto de interés
LoMap <-- Proveedor: Devuelve einformación del punto

Usuario <-- LoMap: Muestra información del punto de interés

Usuario -> LoMap: Publica comentario

LoMap -> Proveedor: Solicita acceso al pod del amigo
Proveedor -> PodAmigo: Envía la información del comentario
LoMap <-- Proveedor: Confirma la creación del comentario

Usuario <-- LoMap: Muestra el comentario en pantalla

----

