[[section-technical-risks]]
== Riesgos y Deuda Técnica


[role="arc42help"]
****
.Contents
A list of identified technical risks or technical debts, ordered by priority

.Motivation
“Risk management is project management for grown-ups” (Tim Lister, Atlantic Systems Guild.) 

This should be your motto for systematic detection and evaluation of risks and technical debts in the architecture, which will be needed by management stakeholders (e.g. project managers, product owners) as part of the overall risk analysis and measurement planning.

.Form
List of risks and/or technical debts, probably including suggested measures to minimize, mitigate or avoid risks or reduce technical debts.
****

[cols="1,4"]
.Riesgos
|==============
| Riesgo | Descripción
| Trabajar con React | No hemos trabajado con el framework y va a ser muy necesario estar informándonos constantemente
| JavaScript | Aunque hayamos trabajado con ella anteriormente, no lo hemos hecho con mucha profundidad y aún tenemos que mejorar y aprender más.
| Uso de SOLID y sus Pods | Es una tecnología que desconocemos por completo y deberemos aprender
| Miembros del equipo desconocidos | Contamos con 4 miembros en el equipo, no nos concemos entre nosotros y deberemos mantener una buena comunicación
| Tiempo | Obviamente tenemos el tiempo reducido, además de que todos tenemos más asignaturas a las que debemos también darle nuestro tiempo
|==============