name: CI for LOMAP ES4B

on:
  release:
    types: [published]
    
  pull_request:
    branches:
      - master
      - develop
  
  push:
    branches:
      - master
      - develop

jobs:
  unit-e2e-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm --prefix webapp ci --legacy-peer-deps
    - run: npm --prefix webapp test --coverage --watchAll
    # - run: CI=false && npm --prefix webapp run build
    # - run: npm --prefix webapp run test:e2e --coverage --watchAll
    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@v1.8
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker-push-webapp:
    name: Push webapp Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    needs: [unit-e2e-tests]
    steps:
    - uses: actions/checkout@v3
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      env:
        API_URI: http://${{ secrets.DEPLOY_HOST }}:5000/api
      with:
          name: arquisoft/lomap_es4a/webapp
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PUSH_TOKEN }}
          registry: ghcr.io
          workdir: webapp
          buildargs: API_URI